"""Add order_id to expenses and add unit_price to order_lens

Revision ID: 8c2b7160f112
Revises: ba165edef848
Create Date: 2025-07-05 18:08:19.672386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2b7160f112'
down_revision = 'ba165edef848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_expenses_order_id', 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_order_id', type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
